# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=""

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git virtualenv sublime zsh-syntax-highlighting)

# lazy loading
lazy_source () {
    eval "$1 () { [ -f $2 ] && source $2 && $1 \$@ }"
}

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/home/malithsen/mongodb/mongodb-linux-i686-2.4.10/bin:/home/malithsen/.gem/ruby/2.4.0/bin
### Cordova dependencies
export ANDROID_HOME="/home/malithsen/projects/java/adt/sdk"
export ANT_HOME="/home/malithsen/projects/java/adt/apache-ant"
export PATH="$ANT_HOME/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH"

### Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Custom paths
export PATH="/home/malithsen/bin:$PATH"

#gradle AEAS
export GRADLE_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=9999,server=y,suspend=n"
export RUN_ENVIRONMENT='dev'

source /home/malithsen/bin/z.sh

#if [[ -r /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh ]]; then
#    source /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh
#fi

### Aliases ###

# Generated by Betty's install script
alias adoh=/home/malithsen/betty/main.rb

alias idea=/home/malithsen/projects/java/intellij-ultimate/bin/idea.sh
alias subl=/home/malithsen/bin/sublime_text
alias score="curl http://static.cricinfo.com/rss/livescores.xml >/dev/null 2>&1 | grep -m 1 'Sri Lanka' | grep -o -P '(?<=\>).*(?=\<)'"

### RANGER CONFIGS ###
export EDITOR='vim'

# nvm
export NVM_DIR="/home/malithsen/.nvm"
NVM_SOURCE=$NVM_DIR/nvm.sh
lazy_source nvm $NVM_SOURCE

# virtualenv and virtualenvwrapper
export WORKON_HOME=/home/malithsen/.virtualenvs
source /usr/bin/virtualenvwrapper_lazy.sh

#go appengine
export PATH="/home/malithsen/bin/go_appengine:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Initialise prompt system
autoload -Uz promptinit
promptinit
prompt pure

